import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, test } from "vitest";

const identity = JSON.parse(
  readFileSync(new URL("../../config/extension-identity.json", import.meta.url), "utf8")
) as {
  chromeManifestKey: string;
  chromeExtensionId: string;
  oauthCallbackPath: string;
  oauthRedirectUrl: string;
};

describe("Accord Guard stable Chrome identity", () => {
  test("derives the documented extension ID from the checked-in public manifest key", () => {
    expect(deriveChromeExtensionId(identity.chromeManifestKey)).toBe(identity.chromeExtensionId);
    expect(identity.chromeExtensionId).toMatch(/^[a-p]{32}$/);
  });

  test("documents the OAuth callback generated by chrome.identity", () => {
    expect(identity.oauthCallbackPath).toBe("auth/callback");
    expect(identity.oauthRedirectUrl).toBe(`https://${identity.chromeExtensionId}.chromiumapp.org/auth/callback`);
  });
});

function deriveChromeExtensionId(manifestKey: string) {
  const publicKeyDer = Buffer.from(manifestKey, "base64");
  const idHex = createHash("sha256").update(publicKeyDer).digest("hex").slice(0, 32);
  return idHex.replace(/[0-9a-f]/g, (char) => String.fromCharCode("a".charCodeAt(0) + Number.parseInt(char, 16)));
}
